#!/usr/bin/env python3
"""Convert a Galdurino 22V10 dump to a JEDEC file.

Handles the file's UTF-8 CR-symbol trailing characters (U+240D).
Port of JEDFile.java for chip id 0x48/0x49.
"""

import sys

# From GALHandler.java line 15
CFG22V10 = [5809,5808,5811,5810,5813,5812,5815,5814,5817,5816,
            5819,5818,5821,5820,5823,5822,5825,5824,5827,5826]

CR_SYMBOL = b'\xe2\x90\x8d'

def parse_dump(path):
    with open(path, 'rb') as f:
        raw = f.read()
    lines = [l.replace(CR_SYMBOL, b'').replace(b'\r', b'').decode('utf-8','replace').rstrip()
             for l in raw.split(b'\n')]

    fs = us = cs = -1
    for i, l in enumerate(lines):
        if l == "FUSEMAP:": fs = i + 1
        elif l == "UES:": us = i
        elif l == "CFG:": cs = i + 1

    fuse_rows = [l for l in lines[fs:us] if len(l) == 138 and set(l) <= set("01")]
    ues = lines[us + 1] if us > 0 else ""
    cfg = lines[cs] if cs > 0 else ""

    return {
        'fuse_rows': fuse_rows,
        'ues': ues,
        'cfg': cfg,
    }


def build_jed(parsed):
    QF = 5892
    UES_OFFSET = 5828  # per GALHandler.java 22V10

    rows = parsed['fuse_rows']
    if len(rows) != 44:
        raise ValueError(f"expected 44 fuse rows, got {len(rows)}")

    # Java parser uses only first 132 chars per row (fuses[44][132])
    fuses = [0] * QF

    # Column-major: JED[i + j*44] = row[i][col=j]
    for i in range(44):
        row = rows[i][:132]
        for j in range(132):
            fuses[i + j * 44] = 1 if row[j] == '1' else 0

    # UES 64 bits
    ues = parsed['ues'][:64] if parsed['ues'] else ""
    for i, c in enumerate(ues):
        if c in '01':
            fuses[UES_OFFSET + i] = int(c)

    # CFG bits scattered
    cfg = parsed['cfg'][:20] if parsed['cfg'] else ""
    for i, c in enumerate(cfg):
        if c in '01' and i < len(CFG22V10):
            fuses[CFG22V10[i]] = int(c)

    return fuses


def fuse_checksum(fuses):
    c = 0; e = 0; a = 0
    for bit in fuses:
        e += 1
        if e == 9:
            e = 1; a += c; c = 0
        c >>= 1
        if bit: c += 0x80
    return (c >> (8 - e)) + a


def write_jed(fuses, out_path, linewidth=44):
    QF = len(fuses)
    lines = []
    lines.append("Generated by gald2jed_22v10.py")
    lines.append("*")
    lines.append(f"QP24* QF{QF}* QV0* F0*")

    body = " X0"
    line_start = 0
    for i, bit in enumerate(fuses):
        if i % linewidth == 0:
            body += f"*\nL{line_start:04d} "
            line_start += linewidth
        body += str(bit)
    body += "*"
    lines.append(body)
    lines.append(f"C{fuse_checksum(fuses):04X}*")

    text = "\n\r".join(lines) + "\n\r"
    payload = b"\x02" + text.encode() + b"\x03"
    payload += f"{sum(payload) & 0xFFFF:04X}\n\r".encode()

    with open(out_path, 'wb') as f:
        f.write(payload)


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gald2jed_22v10.py <input.dump> <output.jed>")

    p = parse_dump(sys.argv[1])
    print(f"fuse rows: {len(p['fuse_rows'])}")
    print(f"UES:  {len(p['ues'])} chars")
    print(f"CFG:  {len(p['cfg'])} chars")

    fuses = build_jed(p)
    print(f"total fuses: {len(fuses)} ({fuses.count(0)} zeros, {fuses.count(1)} ones)")

    write_jed(fuses, sys.argv[2])
    print(f"wrote {sys.argv[2]}")


if __name__ == "__main__":
    main()
