#!/usr/bin/env python3
"""Convert a Galdurino serial dump (GAL: / VENDOR: / PES: / FUSEMAP: / UES: /
CFG: / END sections) into a proper JEDEC .jed file.

Port of JEDFile.java. Currently supports GAL16V8B/C/D (chip ID 1A/1B).
Extend for 20V8/22V10 when needed.

Usage:
    ./gald2jed.py <input.dump> <output.jed>
"""

import sys, os

# cfg16v8bcd mapping from GALHandler.java line 12 - physical config bit → JED fuse address
CFG16V8BCD = [2048,2049,2050,2051,2193,2120,2121,2122,2123,2128,2129,2130,2131,
              2132,2133,2134,2135,2136,2137,2138,2139,2140,2141,2142,2143,2144,
              2145,2146,2147,2148,2149,2150,2151,2152,2153,2154,2155,2156,2157,
              2158,2159,2160,2161,2162,2163,2164,2165,2166,2167,2168,2169,2170,
              2171,2172,2173,2174,2175,2176,2177,2178,2179,2180,2181,2182,2183,
              2184,2185,2186,2187,2188,2189,2190,2191,2124,2125,2126,2127,2192,
              2052,2053,2054,2055]


def parse_dump(path):
    with open(path, 'rb') as f:
        raw = f.read()
    lines = [l.decode('utf-8', 'replace').rstrip('\r\n').rstrip() for l in raw.split(b'\n')]

    idx = {}
    for i, l in enumerate(lines):
        if l == "GAL:": idx['gal'] = i + 1
        elif l == "VENDOR:": idx['vnd'] = i + 1
        elif l == "PES:": idx['pes'] = i + 1
        elif l == "FUSEMAP:": idx['fs'] = i + 1
        elif l == "UES:": idx['us'] = i
        elif l == "CFG:": idx['cfg'] = i + 1
        elif l == "END": idx['end'] = i

    gal_id = int(lines[idx['gal']], 16)
    vendor = lines[idx['vnd']]
    pes    = lines[idx['pes']]
    fuse_rows = [l for l in lines[idx['fs']:idx['us']] if len(l) > 20]
    ues    = lines[idx['us'] + 1]
    cfg    = lines[idx['cfg']]

    return {
        'gal_id': gal_id, 'vendor': vendor, 'pes': pes,
        'fuse_rows': fuse_rows, 'ues': ues, 'cfg': cfg,
    }


def build_jed_16v8bcd(parsed):
    """Build a linear fuse array (list of 0/1 ints) for GAL16V8B/C/D.
    Total 2194 fuses. First 2048 = fuse array (32×64), 2048-2055 = UES,
    2056-2119 = extra, 2120-2193 = CFG bits scattered per cfg16v8bcd map."""
    QF = 2194
    UES_OFFSET = 2056  # per GALHandler.java

    # Verify shape
    rows = parsed['fuse_rows']
    if len(rows) != 32:
        raise ValueError(f"expected 32 fuse rows, got {len(rows)}")
    if not all(len(r) == 64 for r in rows):
        raise ValueError(f"expected 64 chars per row, got widths {set(len(r) for r in rows)}")

    fuses = [0] * QF

    # Column-major flatten: JED[i + j*32] = row[i][j]
    for i in range(32):
        for j in range(64):
            fuses[i + j * 32] = 1 if rows[i][j] == '1' else 0

    # UES: 64 bits at offset 2056
    ues = parsed['ues']
    if len(ues) != 64:
        raise ValueError(f"expected 64-char UES, got {len(ues)}")
    for i, c in enumerate(ues):
        fuses[UES_OFFSET + i] = 1 if c == '1' else 0

    # CFG bits scattered per cfg16v8bcd
    cfg = parsed['cfg']
    if len(cfg) < len(CFG16V8BCD):
        raise ValueError(f"CFG too short: {len(cfg)} < {len(CFG16V8BCD)}")
    for i, target in enumerate(CFG16V8BCD):
        fuses[target] = 1 if cfg[i] == '1' else 0

    return fuses


def fuse_checksum(fuses):
    """From JEDFile.java line 75, copied from galblast."""
    c = 0
    e = 0
    a = 0
    for bit in fuses:
        e += 1
        if e == 9:
            e = 1
            a += c
            c = 0
        c >>= 1
        if bit:
            c += 0x80
    return (c >> (8 - e)) + a


def write_jed(fuses, out_path, linewidth=32, gal_name="GAL16V8B/C/D", QP=20):
    """Emit a JEDEC file matching the format produced by JEDFile.saveJED."""
    QF = len(fuses)
    checksum = fuse_checksum(fuses)

    lines = []
    lines.append("Generated by gald2jed.py")
    lines.append("*")
    lines.append(f"QP{QP}* QF{QF}* QV0* F0*")

    body = " X0"
    line_start = 0
    for i, bit in enumerate(fuses):
        if i % linewidth == 0:
            body += f"*\nL{line_start:04d} "
            line_start += linewidth
        body += str(bit)
    body += "*"
    lines.append(body)
    lines.append(f"C{checksum:04X}*")

    stx = b"\x02"
    etx = b"\x03"

    text = "\n\r".join(lines) + "\n\r"
    payload = stx + text.encode() + etx

    # 16-bit transmission checksum: sum of all bytes including STX & ETX
    tsum = sum(payload) & 0xFFFF
    payload += f"{tsum:04X}\n\r".encode()

    with open(out_path, "wb") as f:
        f.write(payload)


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gald2jed.py <input.dump> <output.jed>")

    parsed = parse_dump(sys.argv[1])
    print(f"chip id: 0x{parsed['gal_id']:02X}  vendor: {parsed['vendor']}")

    if parsed['gal_id'] not in (0x00, 0x1A, 0x1B):
        sys.exit(f"only 16V8 supported so far, chip id 0x{parsed['gal_id']:02X} not implemented")

    fuses = build_jed_16v8bcd(parsed)
    zeros = fuses.count(0)
    ones  = fuses.count(1)
    print(f"fuses total: {len(fuses)} = {zeros} zeros + {ones} ones")

    write_jed(fuses, sys.argv[2])
    print(f"wrote {sys.argv[2]}")


if __name__ == "__main__":
    main()
